version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run size
