version: 2.1

jobs:
  all:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run size
      - run: npm run integration

workflows:
  version: 2
  commit:
    jobs:
      - all
  schedule:
    jobs:
      - all
    triggers:
      - schedule:
          cron: "40 * * * *"
          filters:
            branches:
              only:
                - master
                - ci-integration-tests
